[package]
name = "powerpals-macaddr"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
mac_address = { version = "1.1.8", features = ["serde"] }
diesel = { version = "2", features = ["postgres_backend"] }
anyhow = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
